package principal;

import view.FabricanteView;
import view.PacienteView;
import view.UnidadeSaudeView;
import view.UsuarioView;
import view.VacinacaoView;
import view.VacinadoresView;

public class FormMenu extends javax.swing.JFrame {

    public FormMenu() {
        System.out.println(getClass().getResource("/imagens/primeiro.png"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        miUsuario = new javax.swing.JMenuItem();
        miPacientes = new javax.swing.JMenuItem();
        miUnidadeSaude = new javax.swing.JMenuItem();
        miVacinacao = new javax.swing.JMenuItem();
        miFabricantes = new javax.swing.JMenuItem();
        miVacinadores = new javax.swing.JMenuItem();
        menuOpcoes = new javax.swing.JMenu();
        menuItemSair = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastro.setText("Cadastros");

        miUsuario.setText("Usuários");
        miUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuarioActionPerformed(evt);
            }
        });
        menuCadastro.add(miUsuario);

        miPacientes.setText("Pacientes");
        miPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPacientesActionPerformed(evt);
            }
        });
        menuCadastro.add(miPacientes);

        miUnidadeSaude.setText("Unidade Saúde");
        miUnidadeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnidadeSaudeActionPerformed(evt);
            }
        });
        menuCadastro.add(miUnidadeSaude);

        miVacinacao.setText("Vacinação");
        miVacinacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVacinacaoActionPerformed(evt);
            }
        });
        menuCadastro.add(miVacinacao);

        miFabricantes.setText("Fabricantes");
        miFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFabricantesActionPerformed(evt);
            }
        });
        menuCadastro.add(miFabricantes);

        miVacinadores.setText("Vacinadores");
        miVacinadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVacinadoresActionPerformed(evt);
            }
        });
        menuCadastro.add(miVacinadores);

        jMenuBar1.add(menuCadastro);

        menuOpcoes.setText("Opções");

        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuOpcoes.add(menuItemSair);

        jMenuBar1.add(menuOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuarioActionPerformed
        UsuarioView objusu = null;
        objusu = new UsuarioView();
        objusu.setVisible(true);
    }//GEN-LAST:event_miUsuarioActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void miPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPacientesActionPerformed
        PacienteView objpac = null;
        objpac = new PacienteView();
        objpac.setVisible(true);
    }//GEN-LAST:event_miPacientesActionPerformed

    private void miVacinacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVacinacaoActionPerformed
        VacinacaoView objvnc = null;
        objvnc = new VacinacaoView();
        objvnc.setVisible(true);
    }//GEN-LAST:event_miVacinacaoActionPerformed

    private void miFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFabricantesActionPerformed
        FabricanteView objfab = null;
        objfab = new FabricanteView();
        objfab.setVisible(true);
    }//GEN-LAST:event_miFabricantesActionPerformed

    private void miVacinadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVacinadoresActionPerformed
        VacinadoresView objvac = null;
        objvac = new VacinadoresView();
        objvac.setVisible(true);
    }//GEN-LAST:event_miVacinadoresActionPerformed

    private void miUnidadeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnidadeSaudeActionPerformed
        UnidadeSaudeView objunis = null;
        objunis = new UnidadeSaudeView();
        objunis.setVisible(true);
    }//GEN-LAST:event_miUnidadeSaudeActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenu menuOpcoes;
    private javax.swing.JMenuItem miFabricantes;
    private javax.swing.JMenuItem miPacientes;
    private javax.swing.JMenuItem miUnidadeSaude;
    private javax.swing.JMenuItem miUsuario;
    private javax.swing.JMenuItem miVacinacao;
    private javax.swing.JMenuItem miVacinadores;
    // End of variables declaration//GEN-END:variables
}
